### ISSUE TITLE
InApp messages transaction too Large

### ISSUE THREAD

**Issue by cernfr1993** [exponea/exponea-android-sdk#52] opened 2022-11-07 09:31 UTC
Hi,

recently we start to use Exponea InAppMessages feature. After some time we noticed that our app start crashing on TransactionTooLargeException. The crashes have significant increase when InApp messages are active in our Android app.
We could not find any big transactions in our application and we could not replicate this problem either. :/

Please, could you check your Android library?

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/4852900/200530268-0f7d816c-752a-46c0-847b-50133cc4218c.png)

<img width="603" alt="image" src="https://user-images.githubusercontent.com/4852900/200274797-e38d2c2c-f88b-4a4f-87c1-7bc6f50b28bd.png">

Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 530552 bytes
       at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Caused by android.os.TransactionTooLargeException: data parcel size 530552 bytes
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:635)
       at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1358)
       at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Thank You.

**Comment by adam1929** [comment] 2022-11-11 14:37
Hi @cernfr1993 thank you for your reporting, unfortunately this is issue in SDK itself. We plan to prevent these issue in next releases. Unfortunately this problem has no easy to fix, because we want to use standardised ways to use Android Views, and this problem may be fixed only by some architectural changes.
Main problem here is, that in case of large content of InApp is sending to particular part of code (opening InApp with Activity/Fragment), system is killing it to some limitations -> this is result of our internal analysis.
Please check if you are using some really large InApp messages, especially builded by HTML editor, check for large images there or so.

**Comment by cernfr1993** [comment] 2022-11-14 07:41
Thank you for your response.
We do not use HTML builder in our inAppMessages and image has only 94 kB. I spouse image is not causing the problem. We also noticed this type of problem:

Caused by java.io.NotSerializableException
pn.b
java.io.ObjectOutputStream.writeObject0 (ObjectOutputStream.java:1240)

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/4852900/201602170-8b41f22c-fab9-4d6c-b974-a448d193f120.png">

I hope it will help you.

Thank you.

**Comment by adam1929** [comment] 2022-11-15 13:25
Hi @cernfr1993 thank you for more info.
Unfortunatelly we are not able to reproduce this error. We tried large HTML inapps, large images and very long content in model InApps, but with no luck. Please do you have some stacktraces with SDK lines? Because we are not able to detect problem directly.
Stacktrace readiness is also needed for second problem with obfuscated 'pn.c' class. Is it SDK related?
If you want to share some code with us but is sensitive, please ask our support. Thank you

**Comment by adam1929** [comment] 2022-12-14 08:44
Hi @cernfr1993 I'm not seeing any relation of Exception and InApps from your log.
Log is saying that InAppMessageManager is searching for InApp for 'page_visit' event, and that is done on every page_visit event track - that is correct.
As you can see in logs there are messages such as '0 messages available after filtering' etc. This means obviously that there are no messages to be shown, so it don't try to open any Activity from SDK (for InApp showing purpose).

Honestly, there are some possible improvements in SDK for this case of high frequency tracking, but I doubt that change will help == SDK is using daemon threads for showing InApp message and these daemon threads holds some runtime resources.  They need to. But chaining them is not a solution in this case, because multiple events tracking will hold that chain for no reason here and other InApp showing will be delayed too much.
Please try to find out why 'page_visit' is tracking so often and reduce that.

**Closed** 2023-02-07 08:01 UTC
