### ISSUE TITLE
Problem with Robolectric

### ISSUE THREAD

**Issue by MitroshinDmitry** [exponea/exponea-android-sdk#12] opened 2019-01-18 11:36 UTC
When i was try to add Robolectric test to our project, i was encountered with IllegalArgumentException.
Below you can find test project, where that problem was arise.
If you remove dependency from exponea module - the problem will disappear.
When i try to add exponea module manually (by downloading a source code) - problem also not reproduce.
[RobolectricDemo.zip](https://github.com/exponea/exponea-android-sdk/files/2772757/RobolectricDemo.zip)

**Comment by chnt** [comment] 2019-02-04 15:10
Hi @MitroshinDmitry it looks like your automated tests stops without the system reaching or even referencing the Exponea library.

**Comment by nickskull** [comment] 2019-02-04 16:22
Since this issue is not caused by the SDK, we're closing it. Let us know if you encounter any issues related to the SDK.

**Closed by nickskull** 2019-02-04 16:22 UTC

**Comment by a-change** [comment] 2019-02-25 18:00
Looks like [this solution](https://stackoverflow.com/questions/53987300/robolectric-test-throwing-illegalargumentexception-with-no-message) should help.

**Comment by MitroshinDmitry** [comment] 2019-02-26 11:00
> Looks like [this solution](https://stackoverflow.com/questions/53987300/robolectric-test-throwing-illegalargumentexception-with-no-message) should help.

 Thanks! It's work for me
