### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException in the InAppMessagePresenter

### ISSUE THREAD

**Issue by red5leader** [exponea/exponea-android-sdk#44] opened 2021-12-09 03:21 UTC
Our app is currently using the `2.9.5` version of the sdk and we are receiving the following crash alerts in Firebase. It's occurring on multiple types of devices as well as different Android OS versions

![2021-12-08_22-18-44](https://user-images.githubusercontent.com/59453706/145328432-eb751bf3-a565-428b-a1f9-aa6521f9b28b.png)

Is this something that may have been fixed in a new version of the sdk or something that may have been reported before?

**Comment by michaela-dev** [comment] 2021-12-09 08:56
Hi, this should be fixed in 2.9.7, this was caused by the in-app autoclose feature where SDK was trying to close in-app after a specific time and its window was no longer available (was already destroyed).

**Closed by michaela-dev** 2021-12-09 08:56 UTC
